# Generated by Django 4.2.3 on 2023-07-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaTareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='completado',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='titulo',
            new_name='title',
        ),
    ]
