# Generated by Django 4.2.3 on 2023-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaTareas', '0002_rename_completado_lista_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
